### ISSUE TITLE
Upstream bug in Moo 1.003000 (was: compilation errors ubuntu 13.04 64bit)

### ISSUE THREAD

**Issue by pomalin** [alexrj/Slic3r#1330]
Hello, I have this errors when compiling today ;
App::cpanminus is up to date. (1.6924)
Boost::Geometry::Utils is up to date. (0.15)
Class::XSAccessor is up to date. (1.18)
Encode::Locale is up to date. (1.03)
skipping R/RJ/RJBS/perl-5.18.0.tar.gz
File::Spec is up to date. (3.40)
Getopt::Long is up to date. (2.41)
Growl::GNTP is up to date. (0.20)
IO::Scalar is up to date. (2.110)
Math::Clipper is up to date. (1.22)
Math::ConvexHull::MonotoneChain is up to date. (0.01)
Math::Geometry::Voronoi is up to date. (1.3)
Math::PlanePath is up to date. (107)
Moo is up to date. (1.003000)
Scalar::Util is up to date. (1.27)
Storable is up to date. (2.45)
Test::More is up to date. (0.98)
Time::HiRes is up to date. (1.9725)
XML::SAX::ExpatXS is up to date. (1.33)
--> Working on SMUELLER/ExtUtils-ParseXS-3.18_04.tar.gz
Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-ParseXS-3.18_04.tar.gz ... OK
Configuring ExtUtils-ParseXS-3.18_04 ... OK
Building and testing ExtUtils-ParseXS-3.18_04 ... OK
Successfully installed ExtUtils-ParseXS-3.18_04
1 distribution installed
--> Working on ./xs
Configuring /home/manu/Bureau/reprap/Slic3r/xs ... OK
Building and testing Slic3r-XS-0.01 ... OK
Successfully installed Slic3r-XS-0.01
1 distribution installed
t/angles.t ........... ok  
t/arcs.t ............. ok  
t/clean_polylines.t .. ok  
t/clipper.t .......... ok  
t/collinear.t ........ ok  
t/combineinfill.t .... ok  
t/cooling.t .......... ok  
t/custom_gcode.t ..... ok  
t/dynamic.t .......... skipped: variable-width paths are currently disabled
t/fill.t ............. 2/10 Thread 3 terminated abnormally: Deep recursion on subroutine "Slic3r::Fill::Base::new" at /usr/local/share/perl/5.14.2/Sub/Defer.pm line 41.
Thread 4 terminated abnormally: Deep recursion on subroutine "Slic3r::Fill::Base::new" at /usr/local/share/perl/5.14.2/Sub/Defer.pm line 41.
t/fill.t ............. ok  
t/freeze.t ........... Thread 4 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 67) line 29.
t/freeze.t ........... ok  
t/gcode.t ............ ok  
t/geometry.t ......... ok  
t/layers.t ........... Thread 3 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 68) line 29.
t/layers.t ........... 1/5 Thread 8 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/layers.t ........... 2/5 Thread 12 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/layers.t ........... 3/5 Thread 16 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/layers.t ........... ok  
t/loops.t ............ ok  
t/perimeters.t ....... ok  
t/polyclip.t ......... ok  
t/print.t ............ ok  
t/retraction.t ....... Thread 4 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 67) line 29.
t/retraction.t ....... 1/16 Thread 7 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 2/16 Thread 12 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/retraction.t ....... 3/16 Thread 16 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/retraction.t ....... 4/16 Thread 20 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/retraction.t ....... 5/16 Thread 23 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 6/16 Thread 27 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 7/16 Thread 31 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 8/16 Thread 36 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/retraction.t ....... 9/16 Thread 39 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 10/16 Thread 44 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/retraction.t ....... 11/16 Thread 47 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 12/16 Thread 51 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 13/16 Thread 56 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 86) line 29.
t/retraction.t ....... 14/16 Thread 59 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... 15/16 Thread 63 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 87) line 29.
t/retraction.t ....... ok  
t/serialize.t ........ ok  
t/shells.t ........... Thread 4 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 67) line 29.
t/shells.t ........... 1/3 
# Failed test 'wrong number of top solid layers'
# at t/shells.t line 38.

Thread 7 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 83) line 29.
t/shells.t ........... 3/3 
# Failed test 'wrong number of bottom solid layers'
# at t/shells.t line 36.
# Failed test 'wrong number of top solid layers'
# at t/shells.t line 38.

Thread 11 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 83) line 29.
Thread 12 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 84) line 29.
t/shells.t ........... 6/3 
# Failed test 'correct number of top solid shells is generated in V-shaped object'
# at t/shells.t line 67.
# got: '0'
# expected: '3'
# Looks like you planned 3 tests but ran 6.
# Looks like you failed 4 tests of 6 run.

t/shells.t ........... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 2/3 subtests 
t/skirt_brim.t ....... Thread 6 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 67) line 29.
Thread 5 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 68) line 29.
t/skirt_brim.t ....... ok  
t/slice.t ............ ok  
t/support.t .......... Thread 3 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 64) line 29.
Thread 4 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 68) line 29.
Thread 5 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 67) line 29.
Thread 6 terminated abnormally: Deep recursion on subroutine "Slic3r::Flow::new" at (eval 67) line 29.
t/support.t .......... ok  
t/svg.t .............. ok  
t/vibrationlimit.t ... ok   
## Test Summary Report

t/shells.t         (Wstat: 1024 Tests: 6 Failed: 5)
  Failed tests:  1, 3-6
  Non-zero exit status: 4
  Parse errors: Bad plan.  You planned 3 tests but ran 6.
Files=26, Tests=200, 49 wallclock secs ( 0.10 usr  0.04 sys + 53.88 cusr  0.83 csys = 54.85 CPU)
Result: FAIL
