### ISSUE TITLE
./xs failed

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2973]
What can I do to compile? Everything has been working perfectly and compiling up to now.

![screen shot 07-03-15 at 11 37 pm](https://cloud.githubusercontent.com/assets/9621044/8501020/a2eca0a4-21dc-11e5-9bf9-c1b0b0afdfef.JPG)

**Comment by a4jp-com** [comment]
![screen shot 07-04-15 at 12 14 am 001](https://cloud.githubusercontent.com/assets/9621044/8501587/f19adc0c-21e1-11e5-85e2-4c2910ec788a.JPG)
![screen shot 07-04-15 at 12 15 am](https://cloud.githubusercontent.com/assets/9621044/8501588/f1b56b12-21e1-11e5-9e3d-472ef732a3a9.JPG)

**Comment by alexrj** [comment]
Hm, I'll need to use `_putenv_s()` on Windows instead of `setenv()`.
https://msdn.microsoft.com/en-us/library/vstudio/eyw7eyfw(v=vs.110).aspx

**Comment by a4jp-com** [comment]
Okay. Thank you. 

I bricked my development version so I don't think I'll be able to do anything until it gets tweaked.

Is there anything I can do or try in the meantime? Is it difficult to switch from `_putenv_s()` to `setenv()`?

**Comment by alexrj** [comment]
You can use the stable branch instead of master.

**Comment by a4jp-com** [comment]
I tried but that was the version before the infill bug or infill rendering bug got fixed. I'll date the files I download next time. Can't wait for a compilable version. Everything is starting to work really well in Slic3r and a bug free version of Marlin is almost ready too ^^

**Comment by alexrj** [comment]
Infill bug?
The stable branch should be stable. If it's not, tell me.

**Comment by a4jp-com** [comment]
The stable version has the problem where the infill lines aren't being drawn properly. You fixed this in the development version before and everything was really good until the porting of Slic3r::GCode to XS (speed boost) was done. 

If you could update the stable version to the point just before the port, or fix the code that doesn't work in Windows in the development version it would be fantastic.

![screen shot 07-04-15 at 06 21 am](https://cloud.githubusercontent.com/assets/9621044/8514298/0a7ef4ba-23c7-11e5-9dbb-efbd9040bb81.JPG)

Is there anything I can do to help?

**Comment by alexrj** [comment]
Can you post a complete report in a separate issue?

**Comment by a4jp-com** [comment]
Okay I'll post the config file and a 3D file in a separate post for the stable version. I'm looking forward to the _putenv_s() though. Everything was working really well before.

**Comment by a4jp-com** [comment]
I don't know if this will help much but it shows where the 'setenv()' values are.

![screen shot 07-09-15 at 05 23 am](https://cloud.githubusercontent.com/assets/9621044/8581308/d4df6dc2-25fa-11e5-821d-5aef513fb4ad.JPG)

**Comment by a4jp-com** [comment]
I figured out a way to compile the files in Windows.

Config.cpp
Line 115: '_putenv_s(envname.c_str(), this->serialize(*it).c_str());'

config.hpp
Line 82: '_putenv_s( name.begin(), value.begin());'


![screen shot 07-09-15 at 05 54 am](https://cloud.githubusercontent.com/assets/9621044/8582174/15a7755c-2600-11e5-8916-94f118bd09b1.JPG)

![screen shot 07-09-15 at 06 01 am](https://cloud.githubusercontent.com/assets/9621044/8582173/15a494e0-2600-11e5-8f3e-6eebf6d67de5.JPG)

**Comment by alexrj** [comment]
Can you confirm this commit works?

**Comment by a4jp-com** [comment]
I'll check now ^^

**Comment by a4jp-com** [comment]
./xs is working now and everything compiles. 

Beautiful coding ^^ 

Thank you so much.

**Comment by llluis** [comment]
Just to let you know that this fix doesn't work with latest versions of CitrusPerl 5.16.3.18 x64 and MiniGW gcc (gcc-4.6.4 release with patches [build 20130519 by perlmingw.sf.net]) 4.6.4.

    src\libslic3r\Config.cpp: In member function 'void Slic3r::ConfigBase::setenv_()':
    src\libslic3r\Config.cpp:117:9: error: '_putenv_s' was not declared in this scope
    error building dll file from 'src\libslic3r\Config.cpp' at     F:/Software/CitrusPerl/lib/ExtUtils/CBuilder/Platform/Windows.pm line 130.
    FAIL
    ! Installing ./xs failed. See D:\DOCUME~1\xy0334\.cpanm\work\1438269404.1384\build.log for  details. Retry with --force to force install it.
    The XS/C++ code failed to compile, aborting


Maybe CitrusPerl should be dropped as supported.

(I was trying to compile on a "restricted" machine with a portable perl installation. Don't know if I'll be able to install Strawberry Perl here)

**Comment by lordofhyphens** [comment]
It is 5.16 that is the problem.

**Comment by llluis** [comment]
RTFM for me!

Trying to find CitrusPerl 5.14 for download. 
strawberryperl.com is offline. 
:(

**Comment by lordofhyphens** [comment]
Probably just want to use the other Windows Perl distribution I think. Or
linux :D

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by Hurricane31337** [comment]
For me, Strawberry Perl v5.22.0 with MinGW gcc 4.6.3 didn't work, either (with or without the changes a4jp-com suggested), but gcc 4.9.5 x64 did (without changes). I guess, it should work with CitrusPerl, as long as a newer gcc version is used.

**Comment by c-born** [comment]
CitrusPerl 5.14 and 5.16, using the default MinGW gcc they install, fail for me on the _putenv_r, which is declared in sec_api/stdlib_r.h and isn't being included.
I tried installing the latest MinGW gcc package and connecting CitrusPerl to it, but that threw up a bunch of new errors.
What versions and flavours of Perl and MinGW are being used for current Windows development testing, so I can get my system in sync?
